name: delete_branch_personal_deployment

# Controls when the workflow will run
on:
  delete:
    branches:
      - feature/*
      - bugfix/*
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  delete_branch_personal_deployment:
    if: ${{github.event.ref_type}} == 'branch'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      PREFIX:

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: prepare-prefix
        run: |
          GITHUB_SHA=${{github.sha}}
          HEAD_SHA=${{github.event.workflow_run.head_sha}}
          echo ${{ toJson(github) }}
          echo ${GITHUB_SHA:0:7}
          echo ${HEAD_SHA:0:7}
       
