name: delete_pull_request_personal_deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  delete_pr_personal_deployment:
    runs-on: ubuntu-latest
    env:
      PULL_REQUEST_PREFIX:
      BRANCH_PREFIX:

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: should-not-exec
        if: ${{github.event.pull_request.head.ref != 'dev'}}
        run: |
          echo "should not be exec"
          echo ${{github.event.pull_request.head.ref}}
      - name: prepare-prefix
        run: |
          GITHUB_SHA=${{github.sha}}
          echo ${{ toJson(github) }}
          echo ${{github.event.pull_request.head.sha}}
          echo "BRANCH_PREFIX=branch-${GITHUB_SHA:0:7}" >> $GITHUB_ENV
          echo "PULL_REQUEST_PREFIX=pr${{github.event.number}}" >> $GITHUB_ENV
    
